# Generated by Django 5.1.6 on 2025-08-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_logindata_registerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'رجالي'), ('women', 'نسائي')], default='men', max_length=10),
        ),
    ]
