# Generated by Django 5.1.6 on 2025-08-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='رقم العملية'),
        ),
    ]
