# Generated by Django 5.1.6 on 2025-08-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='logindata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registerdata',
            name='email',
        ),
        migrations.AddField(
            model_name='logindata',
            name='username',
            field=models.CharField(default='Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'رجالي'), ('women', 'نسائي'), ('kids', 'أطفالي')], default='men', max_length=10),
        ),
    ]
