# Generated by Django 5.1.6 on 2025-08-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customer_email_alter_shippingaddress_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
