# Generated by Django 5.1.6 on 2025-08-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_date_orderd_order_date_ordered_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginData',
        ),
        migrations.DeleteModel(
            name='RegisterData',
        ),
    ]
