# Generated by Django 5.1.6 on 2025-08-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_description_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_of_clothe',
            field=models.CharField(choices=[('t-shirt', 'تي شيرتات'), ('pants', 'بناطلين'), ('jackets', 'جاكيتات'), ('suits', 'بدلات'), ('sportswear', 'ملابس رياضية'), ('jeans', 'جينز'), ('hoodies', 'هوديز'), ('dresses', 'فساتين'), ('blouses', 'بلوزات'), ('abayas', 'عبايات'), ('pajamas', 'بيجامات'), ('sneakers', 'أحذية رياضية'), ('formal-shoes', 'أحذية رسمية'), ('boots', 'بوتات'), ('slippers', 'شباشب'), ('caps', 'كابات'), ('hats', 'قبعات'), ('sunglasses', 'نظارات شمسية'), ('watches', 'ساعات')], default='t-shirt', max_length=20),
        ),
    ]
