# Generated by Django 5.1.6 on 2025-08-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد التأكيد'), ('confirmed', 'تم الدفع'), ('delivering', 'في انتظار التوصيل'), ('delivered', 'تم التوصيل')], default='pending', max_length=20),
        ),
    ]
