# Generated by Django 5.1.6 on 2025-08-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_purchase_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='PurchaseHistory',
        ),
    ]
