# Generated by Django 5.1.6 on 2025-08-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_rename_purchase_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shippingaddress'),
        ),
    ]
