# Generated by Django 5.1.6 on 2025-08-10 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_payment_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.shippingaddress'),
        ),
    ]
