# Generated by Django 5.1.6 on 2025-08-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_payment_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='date_purchased',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='status',
        ),
    ]
