# Generated by Django 5.1.6 on 2025-08-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_payment_shipping_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
    ]
